### ISSUE TITLE
ImportError: libssl.so.1.1

### ISSUE THREAD

**Issue by col-one** [djazo/blender-docker#1]
Hello, 
Thanks for this helpful docker ! 
Once the compilation success everything work fine but in this bundled python there is a missing .so when ssl is imported. 

```
>>> import ssl
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/colin_local/blender-git2/build_dir/bin/2.79/python/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

```
I tried to add `libssl-dev`  to DockerFile but it failed to...

Any fix idea ? 

Thanks a lot

**Comment by djazo** [comment]
Let's see how to build with ssl as static, not shared... I'll get into this in day or two!

**Comment by col-one** [comment]
Thanks !
